# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i2jTL1OKpBuhegg8gOZdqObLhYnLOYoJ

# Análise de Dados Exploratória do Titanic

# 1. Introdução
O RMS Titanic foi um navio de passageiros britânico operado pela empresa White Star Line que afundou no Oceano Atlântico Norte nas primeiras horas da manhã de 15 de abril de 1912, depois de atingir um iceberg durante sua viagem inaugural de Southampton a Nova York. Dos 2.224 passageiros e tripulantes a bordo, mais de 1.500 morreram, tornando o naufrágio um dos desastres marítimos comerciais mais mortais da história moderna em tempos de paz.

Neste estudo iremos explorar um conjunto de dados baseado na lista de passageiros do Titanic editada por Michael A. Findlay, publicada originalmente em Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd, e expandida com a ajuda da comunidade da Internet. Os arquivos HTML originais foram obtidos por Philip Hind (1999) e o dataset descreve o status de sobrevivência de passageiros individuais no Titanic. Ele não contém informações para a tripulação, mas contém idades atuais e estimadas para quase 80% dos passageiros.

## 1.1 Objetivos
O objetivo deste estudo é realizar uma Análise Exploratória dos Dados (Exploratory Data Analysis - EDA) do conjunto de dados titanic3, adaptado pelo autor e disponível em [data/titanic3.csv](https://github.com/profdiegoaugusto/analise-dados/blob/master/Pandas/titanic-eda/data/titanic3.csv) ; a fim de caracterizar o perfil dos sobreviventes do fatídico naufrágio. Especificiamente serão respondidas as seguintes questões de pesquisa:

1.   Qual é o número de Sobreviventes?
2.   Homens ou mulheres tiveram mais chances de sobreviver?
3.   Qual classe social teve mais sobreviventes?
4.   Qual faixa etária teve mais chances de sobreviver?

# 2. Metodologia
Nesta seção será apresentado todo o processo de preparação, organização e limpeza de dados feito no dataset que possui os seguintes dados:

## 2.1. Configuração do Ambiente
"""

import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image # Serve para colocar imagem (apagar) /n utilizado/

"""## 2.2. Leitura dos Dados"""

url = 'https://github.com/profdiegoaugusto/analise-dados/blob/master/Pandas/titanic-eda/data/titanic3.csv'
dados_brutos = pd.read_html(url)

#Passando para dataframe e excluindo coluna Unnamed
dados_brutos = pd.DataFrame = dados_brutos[0]
dados_brutos.pop("Unnamed: 0")

"""## 2.3. Organização e Limpeza dos Dados

### 2.3.1. Visão Geral do Conjunto de Dados
"""

dados_brutos.describe().transpose()

dados_brutos.dtypes

dados_brutos.isnull().sum()

"""### 2.3.2 Remoção de Colunas"""

#Excluindo colunas NOME, BILHETE, CABINE, DESTINO
df_titanic = dados_brutos.drop(["nome","bilhete","cabine","destino"], axis=1)

"""### 2.3.3. Dados Ausentes"""

print('dados nulos: {}'.format(df_titanic.isnull().sum().sum()))
print(df_titanic.isnull().sum())

"""#### 2.3.3.1 Idades Ausentes"""

print('Idade NaN(Entrada): {}'.format(df_titanic['idade'].isnull().sum()))
df_titanic[['idade']]  = df_titanic['idade'].fillna(df_titanic['idade'].mean())
print('Idade NaN(Saida): {}'.format(df_titanic['idade'].isnull().sum()))
df_titanic['idade'] = df_titanic['idade'].astype(int)

df_titanic['idade'].unique()

"""#### 2.3.3.2 Tarifas Ausentes"""

print('Falta Tarifa')
df_titanic[df_titanic['tarifa'].isnull()]

tarifas = df_titanic[(df_titanic['classe'] == 3)  & (df_titanic['sexo'] == 'male') & (df_titanic['idade'] >= 50) & (df_titanic['irmaos_conjuges'] == 0)  & (df_titanic['embarque'] == 'S')]
print('Passageiros com dados (Classe, Sexo, Idade, Embarque) semelhantes ao faltante: {}'.format(len(tarifas)))

df_titanic['tarifa'] = df_titanic['tarifa'].fillna(tarifas['tarifa'].mean())

df_titanic.loc[df_titanic['id_passageiro'] == 1225]

"""#### 2.3.3.3 Portos de Embarque Ausentes"""

df_titanic = df_titanic[df_titanic['embarque'].notna()]

"""#### Dados Ausentes"""

print('dados nulos: {}'.format(df_titanic.isnull().sum().sum()))
print(df_titanic.isnull().sum())

"""## 2.4 Mapeamento de Dados"""

def modificado(coluna,origem):
    modificado = []
    if coluna == 'Classe':
        for coluna in origem:
            if coluna == 1:
                modificado.append('Alta')
            elif coluna == 2:
                modificado.append('Média')
            else:
                modificado.append('Baixa')
        return modificado
    elif coluna == 'Sexo':
        for coluna in origem:
            if coluna == 'male':
                modificado.append('M')
            else :
                modificado.append('F')
        return modificado
    else:
        for coluna in origem:
            if coluna == 'C':
                modificado.append('Cherbourg')
            elif coluna == 'Q':
                modificado.append('Queenstown')
            else:
                modificado.append('Southampton')
        return modificado

df_titanic['classe'] = modificado('Classe',df_titanic['classe'])
df_titanic['sexo'] = modificado('Sexo',df_titanic['sexo'])
df_titanic['embarque'] = modificado('Embarque',df_titanic['embarque'])

df_titanic

"""## 2.5. Feature Engineering"""

df_titanic['total_parentes'] = df_titanic['irmaos_conjuges'] + df_titanic['pais_filhos']
#df_titanic['faixa_etaria'] = df_titanic['faixa_etaria'] + df_titanic['faixa_etaria']

"""### 2.5.1 Total de Parentes"""

df_titanic['total_parentes'].head()

"""### 2.5.2 Faixas Etárias"""

def faixa(df):
    idade = []
    for dados in df: 
        if dados <= 12:
            idade.append('Criança')
        elif (dados > 12) & (dados < 18):
            idade.append('Adolecente')
        elif (dados >= 18) & (dados < 60):
            idade.append('Adulto')
        else:
            idade.append('Idoso')
    return idade
faixa = faixa(df_titanic['idade'])
df_titanic['faixa_etaria'] = faixa

df_titanic.sample(20)

"""# 3. Análise dos Dados

## 3.1. Qual é o número de Sobreviventes?
"""

sobrevivente = df_titanic['sobreviveu'].sum()
total = len(df_titanic)
porcentagem = int(sobrevivente*100/total)

plt.style.use("ggplot")
fig = plt.figure(figsize=(11,6))
fig = df_titanic['sobreviveu'].value_counts().plot.barh()
fig.set_title('Passageiros sobreviventes e mortos')
fig.set_ylabel('Mortes / Sobreviventes')
fig.set_xlabel('Número de Pessoas')
print('Total de Sobreviventes {} ({}%) de {} pessoas'.format(sobrevivente,porcentagem, total))

"""## 3.2. Homens ou mulheres tiveram mais chances de sobreviver?"""

df_sobrevivente = df_titanic.loc[(df_titanic['sobreviveu'] == 1 )]
df_sobrevivente = df_sobrevivente['sexo'].value_counts() 
sum = df_sobrevivente.sum()
a = df_sobrevivente[0]*100/sum
b = df_sobrevivente[1]*100/sum

print('Total Sobreviventes: {} (100%)'.format(sum))
print('Sobreviventes Femininos: {} ({}%)'.format(df_sobrevivente[0], round(a,2)))
print('Sobreviventes Masculinos: {} ({}%)'.format(df_sobrevivente[1], round(b,2)))
print('Conclusão que mulheres tiveram o dobro de chance de sobreviver')

"""## 3.3. Qual classe social teve mais sobreviventes?"""

df_sobrevivente = df_titanic.loc[(df_titanic['sobreviveu'] == 1 )]
df_sobrevivente = df_sobrevivente['classe'].value_counts() 
sum = df_sobrevivente.sum()
a = df_sobrevivente[0]*100/sum
b = df_sobrevivente[1]*100/sum
c = df_sobrevivente[2]*100/sum
df_sobrevivente

print('Total Sobreviventes: {} (100%)'.format(sum))
print('Sobreviventes classe Alta: {} ({}%)'.format(df_sobrevivente[0], round(a,2)))
print('Sobreviventes classe Baixa: {} ({}%)'.format(df_sobrevivente[1], round(b,2)))
print('Sobreviventes classe média: {} ({}%)'.format(df_sobrevivente[2], round(c,2)))

"""## 3.4. Qual faixa etária teve mais chances de sobreviver?"""

df_sobrevivente = df_titanic.loc[(df_titanic['sobreviveu'] == 1 )]
print(len(df_sobrevivente))
df_sobrevivente['faixa_etaria'].value_counts()